name: artem
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "$GITHUB_CONTEXT"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make setup
      - run: make test
      - run: make lint
